gui:
 sidePanelWidth: 0.2 # gives you more space to show things side-by-side
 # Use the mocha catppuccin theme, from https://github.com/catppuccin/lazygit
 theme:
   activeBorderColor:
     - '#89b4fa'
     - bold
   inactiveBorderColor:
     - '#a6adc8'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#313244'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#f38ba8'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'

git:
  pagers:
    - pager: delta --paging=never
